//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptidDemo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CryptidDemo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string ARE_YOU_SURE {
            get {
                return ResourceManager.GetString("ARE_YOU_SURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auth likelyhood: .
        /// </summary>
        internal static string AUTH_LIKLEYHOOD_MESSAGE {
            get {
                return ResourceManager.GetString("AUTH_LIKLEYHOOD_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save ID if none has been generated!.
        /// </summary>
        internal static string CANNOT_SAVE_IF_NOT_GENERATED_ERROR {
            get {
                return ResourceManager.GetString("CANNOT_SAVE_IF_NOT_GENERATED_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot generate card if no ID has been generated or the candidate is incomplete!.
        /// </summary>
        internal static string CANNOT_SAVE_IF_NOT_GENERATED_OR_INCOMPLETE {
            get {
                return ResourceManager.GetString("CANNOT_SAVE_IF_NOT_GENERATED_OR_INCOMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chain ID cannot be empty!.
        /// </summary>
        internal static string CHAIN_ID_EMPTY {
            get {
                return ResourceManager.GetString("CHAIN_ID_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cryptid ID File (*.cid)|*.cid.
        /// </summary>
        internal static string CRYPTID_ID_FILTER {
            get {
                return ResourceManager.GetString("CRYPTID_ID_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        internal static string FPS_CONNECTED {
            get {
                return ResourceManager.GetString("FPS_CONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        internal static string FPS_DISCONNECTED {
            get {
                return ResourceManager.GetString("FPS_DISCONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not connected to a fingerprint scanner!.
        /// </summary>
        internal static string FPS_NOT_CONNECTED_ERROR {
            get {
                return ResourceManager.GetString("FPS_NOT_CONNECTED_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot generate an and ID for an incomplete candidate..
        /// </summary>
        internal static string GeneratorForm_uploadBlockchain_Click_Cannot_generate_an_and_ID_for_an_incomplete_candidate_ {
            get {
                return ResourceManager.GetString("GeneratorForm_uploadBlockchain_Click_Cannot_generate_an_and_ID_for_an_incomplete_" +
                        "candidate_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will replace all the information currently in the form. Do you wish to proceed?.
        /// </summary>
        internal static string INFORMATION_OVERWRITE_WARNING {
            get {
                return ResourceManager.GetString("INFORMATION_OVERWRITE_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Files|*.jpg.
        /// </summary>
        internal static string JPG_FILTER {
            get {
                return ResourceManager.GetString("JPG_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter the password associated with this ID..
        /// </summary>
        internal static string MUST_ENTER_PASSWORD_MESSAGE {
            get {
                return ResourceManager.GetString("MUST_ENTER_PASSWORD_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must choose a .cid file or enter a chain ID.
        /// </summary>
        internal static string NEED_CID_OR_CHAIN_ID_ERROR {
            get {
                return ResourceManager.GetString("NEED_CID_OR_CHAIN_ID_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot generate an and ID for an incomplete candidate..
        /// </summary>
        internal static string NOT_GENERATE_INCOMPLETE_ID_ERROR {
            get {
                return ResourceManager.GetString("NOT_GENERATE_INCOMPLETE_ID_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t verify provided data..
        /// </summary>
        internal static string NOT_VERIFY_ID_ERROR {
            get {
                return ResourceManager.GetString("NOT_VERIFY_ID_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be empty!..
        /// </summary>
        internal static string PASSWORD_EMPTY_ERROR {
            get {
                return ResourceManager.GetString("PASSWORD_EMPTY_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided passwords do not match!.
        /// </summary>
        internal static string PASSWORDS_NOT_MATCH {
            get {
                return ResourceManager.GetString("PASSWORDS_NOT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF File (*.pdf)|*.pdf.
        /// </summary>
        internal static string PDF_FILTER {
            get {
                return ResourceManager.GetString("PDF_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an irreversible operation! Are you sure you wish to replace the ID on the chain (see chain ID field) with the provided information?.
        /// </summary>
        internal static string UPDATE_ID_WARNING {
            get {
                return ResourceManager.GetString("UPDATE_ID_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an Irreversable operation! Proceeding will upload this ID to the blockchain under a new unlinked chain permenantly. Please assure all information is correct..
        /// </summary>
        internal static string UPLOAD_BLOCKCHAIN_WARNING {
            get {
                return ResourceManager.GetString("UPLOAD_BLOCKCHAIN_WARNING", resourceCulture);
            }
        }
    }
}
